### PR TITLE
Move cn-cbor to an external dependency

### PR DESCRIPTION
**Pull request by hildjj**
Pal, can you test this on your system please before merging?

### CODE REVIEW

**Comment by palerikm** [comment]
Ok will do. C make fails miserably on Ubuntu 14.4 LTS. Default version of cmake is 2.8.12.2. Tried to "downgrade" to that version in the CMakeLists.txt. That did not work, assuming some 3.0 features are used. Will upgrade to cmake 3.0 on the Ubuntu box manually, but was hoping to avoid hassle like that.

**Comment by hildjj** [comment]
I think we need 3.0+ to do ExternalProject's, which are perfect for dealing with the CBOR dependency.

**Comment by palerikm** [comment]
Upgrading the machine now from long term support to something fresher. Takes a while..

**Comment by palerikm** [comment]
Hmmm CBOR tests fail with ubuntu

Had to turn off optimalization when building the external cbor lib.

**Pull request merged**
