### PR TITLE
Add doxygen comments in tube.h and spud.h

### PR DESCRIPTION
**Pull request by calvert**
Followed the pattern in ls_*.h.

Ken Calvert    calvert@netlab.uky.edu

### CODE REVIEW

**Comment by hildjj** [comment]
Please add yourself to the AUTHORS file.

**Comment by hildjj** [comment]
By the way, this was _fantastic_ work.  In particular, thank you for pulling the assert's up into /invariant's.

**Comment by hildjj** [comment]
Fixes #14

**Comment by calvert** [comment]
Glad to help.  You were right, it was a good way for me to get familiar(er) with the code.
:-)

On 30 Mar 2015, at 18:24, Joe Hildebrand notifications@github.com wrote:

> By the way, this was fantastic work. In particular, thank you for pulling the assert's up into /invariant's.
> 
> —
> Reply to this email directly or view it on GitHub.

Ken Calvert
Professor
Gartner Group Chair in Network Engineering
Computer Science, University of Kentucky

**Pull request merged**
